#name = "<your-app-name>"
#main = "src/index.ts"
#compatibility_date = "2023-04-29" # edit your date

[[ d1_databases ]]
binding = "DB"
database_name = "d1-ai"
database_id = "73f4c1f1-b432-444c-82c4-bf8dcffe2a7f"
preview_database_id = "DB"
# migrations_dir = "./src/"
